### ISSUE TITLE
CiviMobile on Drupal 10

### ISSUE THREAD

**Issue by thecaribbean** [agileware/civimobileapi#1]
I did a fresh install of CiviCRM 5.72.1 on Drupal 10.2.5 with Composer.  Then installed CiviMobileApi v6.4.1 from within Civicrm.

The Civimobile Checklist reports the Rest path as /libraries/civicrm/core/extern/rest.php but it was installed at /vendor/civicrm/civicrm-core/extern/rest.php.

I've tried a few methods to correct including renaming the path, using a symbolic link and updating the Custom PHP Directory. Nothing works including uninstalling, then reinstalling and Cleaning Caches and Update Paths.

I have the same CiviMobileApi v6.4.1 working with Drupal 7.100 on CiviCRM 5.72.1.

![Civimobile Checklist Screenshot 2024-04-22 220604](https://github.com/agileware/civimobileapi/assets/34045047/5e7a7228-37df-4fa4-8488-972cbff81d24)

**Comment by agileware-justin** [comment]
G'day! Please re-post your issue too, https://lab.civicrm.org/extensions/civimobileapi

This is the Agileware fork of this extension.
